

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Praktika
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SDBEntities : DbContext
{
    public SDBEntities()
        : base("name=SDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<ClientService> ClientService { get; set; }

    public virtual DbSet<Gender> Gender { get; set; }

    public virtual DbSet<Photo> Photo { get; set; }

    public virtual DbSet<ServiceCenter> ServiceCenter { get; set; }

}

}

